### ISSUE TITLE
Suggest changing the 'GitHub Username' field to link

### ISSUE THREAD

**Issue by aurexav** [polkadot-fellows/seeding#39]
Example:

| GitHub Username | Kusama Account ID | Rank |
| :---: | :---: | :---: |
| [gavofyork](https://github.com/gavofyork) | `FcxNWVy5RESDsErjwyZmPCW6Z8Y3fbfLzmou34YZTrbcraL` | 7 |

**Comment by bkchr** [comment]
You mean in the table? 

(It would be nice if you could add more details when you open an issue)

**Comment by acgxv** [comment]
> You mean in the table?
> 
> (It would be nice if you could add more details when you open an issue)

Updated.

**Comment by bkchr** [comment]
Okay, sounds good to me. Will you create a pr?
